### ISSUE TITLE
Unable to load views within VDI session

### ISSUE THREAD

**Issue by bjerrecs** [SDFIdk/skraafoto_frontend#121]
Hi SDFI.

We have a client that relies on skraafoto.dataforsyningen.dk in their daily work and has now switched to a VDI desktop for their work.
Here we are unable to view any of the pictures that accompany the 2d view of the addresses entered. The VDI session is GPU accelerated and we have confirmed this by running 
![image](https://user-images.githubusercontent.com/32055984/216902288-6292850a-d3a7-4baa-b409-d9ec673b1784.png)

We in IT have tried a lot of things and these are our findings:
* it works in Microsoft Edge & not Google Chrome Chrome
* When opening Chrome Dev Tools we see this error in the console
![image](https://user-images.githubusercontent.com/32055984/216902747-aa7995c1-96de-4eeb-8c1e-8157fc93ea9d.png)
* We have tried to disable hardware acceleration but this did not do anything

Anyway, we can provide logs or other ways of reporting this issue to make your life easier?

**Comment by iamfrank** [comment]
Hi @bjerrecs 

Could you provide information on any failed requests when looking into the "Network" tab of Chrome Dev Tools.?

**Comment by bjerrecs** [comment]
No need, we managed to solve it on our end. But for your information nothing was no failed requests in the network tab.

The issue was that a Google Chrome Policy was enabled by mistake, in a non descript policy that disabled the 3DAPIs.
https://chromeenterprise.google/policies/?policy=Disable3DAPIs

This solved our customers issues.
Sorry for the inconvenience. 

Will close the issue here

**Comment by iamfrank** [comment]
Glad to hear a solution was found.
