### ISSUE TITLE
Webtilgængelighed: Knapper viser ´title´-teksten "Icon"

### ISSUE THREAD

**Issue by thomasclausen** [SDFIdk/skraafoto_frontend#221]
Når man holder musen over knapperne med ikoner vises `title`-teksten "Icon".
Knapperne har godt nok `title` attributten sat til eks. "Download billede", "Zoom in", "Mål afstand" osv.
Det er specifikt når man rammer knappens ikon at `title`-teksten er forkert.
![image](https://github.com/user-attachments/assets/30a6d980-4ac6-4bb9-8dcc-be84e5f0a873)

Problemet skyldes at jeres ikoner har et `<title />`-tag, hvilket prioriteres over `title` attributten på knappen
https://skraafoto.dataforsyningen.dk/designsystem-icons-FGS7BUHW.svg
![image](https://github.com/user-attachments/assets/ce415b75-70d8-42f1-8b44-928b3de9c3cf)

Det kan både løses ved at fjerne `title`-tag for ikonet, eller tilføje lidt CSS i stil med:
```CSS
button svg {
    pointer-events: none;
}
```

**Comment by iamfrank** [comment]
Det er et relevant issue. Mener det blev skudt ind i sin tid, fordi nogle valideringsværktøjer råber op, hvis der ikke er title i en svg. Men i dette tilfælde bør vi nok lade menneskelig fornuft overstyre.

**Comment by iamfrank** [comment]
Issuet bliver løst fra næste update af Skråfoto-websitet
